version: '3.9'

services:
  backend:
    container_name: backend
    build: backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - nir-network

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "80:3000"
    restart: always
    networks:
      - nir-network

volumes:
  nir-storage:

networks:
  nir-network:
    name: nir-network
    driver: bridge
